# Starter pipeline
variables:
  Version.MajorMinor: 2.0
  Version.Revision: $[counter(variables['Version.MajorMinor'], 12)]
  VERSION: $(Version.MajorMinor).$(Version.Revision)

trigger:
- main

pool:
  server

steps:

- task: InvokeRESTAPI@1
  inputs:
    connectionType: 'connectedServiceName'
    serviceConnection: 'theNameofIt'
    method: 'POST'
    headers: |
      {
      "Content-Type":"application/json"
      }
    urlSuffix:  '/api/sn_cicd/app_repo/publish?sys_id=9878a2b38d254011055da2f0662dbd27bf7&version=$(VERSION)'
    waitForCompletion: 'false'
#    successCriteria: eq(root['result'][percent_complete], '100')

- task: InvokeRESTAPI@1
  inputs:
    connectionType: 'connectedServiceName'
    serviceConnection: 'theNameofit'
    method: 'POST'
    headers: |
      {
      "Content-Type":"application/json"
      }
    urlSuffix:  '/api/sn_cicd/sc/apply_changes?app_sys_id=9878a2b38d254011055da2f0662dbd27bf7'
    waitForCompletion: 'false'
